# Generated by Django 5.2.4 on 2025-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='init_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='init_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
