# Generated by Django 5.2.4 on 2025-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_subscription_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'content_type__app_label': 'subscription'}, to='auth.permission'),
        ),
    ]
