# Generated by Django 5.2.4 on 2025-11-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0005_alter_subscription_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permission', models.ManyToManyField(limit_choices_to={'codename__in': ['starter', 'professional', 'enterprise'], 'content_type__app_label': 'subscriptions'}, to='auth.permission')),
            ],
            options={
                'permissions': [('starter', 'starter perm'), ('professional', 'professional perm'), ('enterprise', 'enterprise perm')],
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
