# Generated by Django 5.2.4 on 2025-11-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_rename_subscriptions_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='permission',
            new_name='permissions',
        ),
    ]
