# Generated by Django 5.2.4 on 2025-12-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_rename_permission_subscription_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_calls', models.IntegerField()),
                ('storage_mb', models.IntegerField()),
                ('automations', models.IntegerField()),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription')),
            ],
        ),
    ]
