# Generated by Django 5.2.4 on 2026-04-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0022_organization_stripe_customer_id_and_more'),
        ('subscriptions', '0010_alter_subscription_options_planlimit_team_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='currency_symbol',
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='INR', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_annual_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for annual billing (e.g. price_xxxxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_monthly_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for monthly billing (e.g. price_xxxxx)', max_length=100),
        ),
        migrations.AlterField(
            model_name='planlimit',
            name='api_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planlimit',
            name='automations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planlimit',
            name='storage_mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planlimit',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planlimit', to='subscriptions.subscription'),
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('trialing', 'Trialing')], default='incomplete', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='saas.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
            ],
        ),
    ]
