# Generated by Django 5.2.4 on 2026-04-16 16:23

import buckets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0022_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='saas.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=buckets.models.bucket_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='buckets.bucket')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
