# Generated by Django 5.2.4 on 2026-04-16 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_bucket_is_public_fileobject_checksum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileobject',
            options={},
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='size',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fileobject',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='buckets.fileobject')),
            ],
        ),
    ]
