# Generated by Django 5.2.4 on 2026-04-16 16:37

import buckets.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_alter_fileobject_options_remove_fileobject_bucket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileobject',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='fileobject',
            name='bucket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='buckets.bucket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileobject',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='file',
            field=models.FileField(default='', upload_to=buckets.models.bucket_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileobject',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='name',
            field=models.CharField(default='unnamed', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileobject',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileobject',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
