# Generated by Django 5.2.4 on 2026-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_alter_fileobject_options_fileobject_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='quota_mb',
            field=models.IntegerField(default=1024),
        ),
    ]
