# Generated by Django 5.2.4 on 2026-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_bucket_quota_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucket',
            name='last_deployed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
