# Generated by Django 5.2.4 on 2026-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_bucket_is_live_bucket_last_deployed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='distribution_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='edge_status',
            field=models.CharField(default='ready', max_length=20),
        ),
    ]
