# Generated by Django 5.2.4 on 2026-04-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0009_bucket_distribution_id_unique'),
        ('saas', '0022_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('runtime', models.CharField(choices=[('django', 'Python / Django'), ('node', 'Node.js'), ('react', 'React / Next.js'), ('static', 'Static Website')], default='django', max_length=20)),
                ('distribution_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Provisioned'), ('building', 'Building'), ('live', 'Live'), ('error', 'Build Failed'), ('deactivated', 'Offline')], default='ready', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='saas.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='AppDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('logs', models.TextField(blank=True, default='')),
                ('artifact', models.FileField(blank=True, null=True, upload_to='deployments/artifacts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='buckets.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='buckets.app')),
            ],
            options={
                'unique_together': {('app', 'key')},
            },
        ),
    ]
