# Generated by Django 5.2.4 on 2026-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0010_app_appdeployment_environmentvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Artifact Upload'), ('github', 'GitHub Repo')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='runtime',
            field=models.CharField(default='django', max_length=50),
        ),
    ]
