# Generated by Django 5.2.4 on 2026-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0011_app_source_type_app_source_url_alter_app_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='provisioning_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
