# Generated by Django 5.2.4 on 2026-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0012_app_provisioning_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='active_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='process_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
