# Generated by Django 5.2.4 on 2026-04-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0013_app_active_port_app_process_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-created_at'], 'permissions': [('manage_apps', 'Can create, edit or delete apps'), ('deploy_apps', 'Can deploy code to apps'), ('control_apps', 'Can start, stop or restart app processes')]},
        ),
    ]
