# Generated by Django 5.2.4 on 2025-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagevisit",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
