# Generated by Django 5.2.4 on 2025-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0002_alter_pagevisit_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("company", models.CharField(max_length=150)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("company_size", models.CharField(max_length=20)),
                ("preferred_date", models.DateField()),
                ("time_slot", models.CharField(max_length=20)),
                ("use_case", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrialSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("company", models.CharField(max_length=150)),
                ("password_hash", models.CharField(max_length=128)),
                ("company_size", models.CharField(blank=True, max_length=20)),
                ("industry", models.CharField(blank=True, max_length=50)),
                ("terms_accepted", models.BooleanField()),
                ("newsletter_opt_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="PageVisit",
        ),
    ]
