# Generated by Django 5.2.4 on 2025-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0003_demoschedule_trialsignup_delete_pagevisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demoschedule",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1-10", "1–10"),
                    ("11-50", "11–50"),
                    ("51-200", "51–200"),
                    ("201-500", "201–500"),
                    ("500+", "500+"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="demoschedule",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trialsignup",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1–10"),
                    ("11-50", "11–50"),
                    ("51-200", "51–200"),
                    ("201-500", "201–500"),
                    ("500+", "500+"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trialsignup",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tech", "Technology"),
                    ("finance", "Finance"),
                    ("education", "Education"),
                    ("health", "Healthcare"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
