# Generated by Django 5.2.4 on 2025-08-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0005_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="resolve",
            field=models.BooleanField(default=False),
        ),
    ]
