# Generated by Django 5.2.4 on 2025-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0006_contactmessage_resolve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trialsignup",
            name="password_hash",
        ),
        migrations.AddField(
            model_name="trialsignup",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demoschedule",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("500+", "500+"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="demoschedule",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trialsignup",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("500+", "500+"),
                ],
                max_length=20,
            ),
        ),
    ]
