# Generated by Django 5.2.4 on 2025-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0007_remove_trialsignup_password_hash_trialsignup_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demoschedule",
            name="phone",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trialsignup",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
