# Generated by Django 5.2.4 on 2025-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0010_alter_demoschedule_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demoschedule",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="trialsignup",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
