# Generated by Django 5.2.4 on 2025-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0011_alter_demoschedule_phone_alter_trialsignup_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demoschedule",
            name="phone",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="trialsignup",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
