# Generated by Django 5.2.4 on 2025-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0013_alter_demoschedule_phone_alter_trialsignup_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="email_history",
            field=models.TextField(blank=True, default=""),
        ),
    ]
