# Generated by Django 5.2.4 on 2025-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0014_contactmessage_email_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Heroicons SVG path or custom icon class', max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('color', models.CharField(default='indigo', help_text='Tailwind color name, e.g., indigo, pink, blue', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
