# Generated by Django 5.2.4 on 2025-11-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0016_faqsection_quickstartstep_supportcard_tutorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='section',
        ),
        migrations.DeleteModel(
            name='QuickStartStep',
        ),
        migrations.DeleteModel(
            name='SupportCard',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='FAQItem',
        ),
        migrations.DeleteModel(
            name='FAQSection',
        ),
    ]
