# Generated by Django 5.2.4 on 2025-12-25 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0019_remove_usage_org_remove_usage_storage_gb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='active_users',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usage',
            name='api_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='automations_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='reports_generated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='storage_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
