# Generated by Django 5.2.4 on 2026-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0022_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deployment_root',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='storage_limit_mb',
            field=models.IntegerField(default=1024),
        ),
    ]
