# Generated by Django 5.2.4 on 2026-04-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0023_organization_deployment_root_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('manage_members', 'Can manage organization team members'), ('manage_billing', 'Can manage organization subscription and billing'), ('destroy_organization', 'Can delete the organization (Owner Only)')]},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('devel', 'Developer'), ('viewer', 'Viewer')], default='devel', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('org', 'user')},
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='saas.organization')),
            ],
            options={
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas.organizationrole'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_codename', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='saas.organizationrole')),
            ],
            options={
                'unique_together': {('role', 'permission_codename')},
            },
        ),
    ]
