# Generated by Django 5.2.4 on 2025-12-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='views',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
