# Generated by Django 5.2.4 on 2025-12-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_remove_tutorial_views_tutorial_youtube_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='gradient_from',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='gradient_to',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
